/**
 * Staging Chrome QA for Aime AI automation testing guidelines.
 * One real Chrome, headless, one page, no screenshots, renderer cap.
 *
 *   node aime_automation_chrome_qa.mjs
 *
 *   QA_APP=https://app.stage.velvetelves.com
 *   QA_EMAIL / QA_PASSWORD
 *   QA_CHANNEL=chrome
 *   QA_HEADED=1   real window — avoid on this machine
 *   QA_DRAFT=1    click Draft due emails (slow; sends nothing)
 */
import { createRequire } from 'module'
import { mkdirSync, writeFileSync } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const require = createRequire(import.meta.url)
const { chromium } = require('playwright')

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const STAMP = new Date().toISOString().slice(0, 10)
const OUT = process.env.QA_OUT
  ? path.resolve(process.env.QA_OUT)
  : path.join(__dirname, `artifacts_staging_${STAMP}`)
mkdirSync(OUT, { recursive: true })

const EMAIL = process.env.QA_EMAIL || 'crazyaidev20500519@gmail.com'
const PASSWORD = process.env.QA_PASSWORD || 'QWE!@#asd234'
const APP = (process.env.QA_APP || 'https://app.stage.velvetelves.com').replace(/\/$/, '')
const HEADED = process.env.QA_HEADED === '1'
const CHANNEL = process.env.QA_CHANNEL || 'chrome'
const DO_DRAFT = process.env.QA_DRAFT === '1'
const DEAL =
  process.env.QA_DEAL || 'ee6134e7-9753-41cb-b334-770eb8d9e803'
const CLOSING_TASK = 'Buyer Closing Information'

const findings = []
const consoleErrors = []
const pageErrors = []
const failedRequests = []
const guidelineNotes = []

function log(id, result, details = '') {
  findings.push({ id, result, details: String(details).slice(0, 6000) })
  console.log(`[${result}] ${id}${details ? ' — ' + String(details).slice(0, 420) : ''}`)
}

function noteGuideline(msg) {
  guidelineNotes.push(msg)
  console.log(`[GUIDELINE] ${msg}`)
}

async function bodyText(page) {
  try {
    return await page.locator('body').innerText({ timeout: 8000 })
  } catch {
    return ''
  }
}

function scanForbidden(text) {
  const hits = []
  const patterns = [
    /\bLibrary letters\b/i,
    /Hourly library send/i,
    /\bClass A\b/,
    /\bConductor\b/i,
    /written by AI/i,
    /generated by ChatGPT/i,
    /✦ Autopilot/,
  ]
  for (const re of patterns) {
    const m = text.match(re)
    if (m) hits.push(m[0])
  }
  return hits
}

async function closeAime(page) {
  const closeChat = page.getByRole('button', { name: /Close AI chat/i })
  if (await closeChat.isVisible({ timeout: 400 }).catch(() => false)) {
    await closeChat.click({ timeout: 1500 }).catch(() => {})
    await page.waitForTimeout(150)
  }
}

async function dismissOverlays(page) {
  await closeAime(page)
  const labels = [
    /Skip tour/i,
    /Skip for now/i,
    /^Skip$/i,
    /Not now/i,
    /Maybe later/i,
    /Continue to (app|dashboard)/i,
    /Go to Dashboard/i,
    /Close tour/i,
  ]
  for (const name of labels) {
    const btn = page.getByRole('button', { name }).first()
    if (await btn.isVisible({ timeout: 280 }).catch(() => false)) {
      await btn.click({ timeout: 1500 }).catch(() => {})
      await page.waitForTimeout(120)
    }
  }
}

function modal(page) {
  return page.locator('[role="alertdialog"], [role="dialog"]')
}

async function clickVisible(locator, id) {
  const loc = locator.first()
  const ok = await loc.isVisible({ timeout: 8000 }).catch(() => false)
  if (!ok) {
    log(id, 'FAIL', 'not visible')
    return false
  }
  await loc.scrollIntoViewIfNeeded().catch(() => {})
  try {
    await loc.click({ timeout: 8000 })
    log(id, 'PASS')
    return true
  } catch (err) {
    log(id, 'FAIL', err.message)
    return false
  }
}

async function waitForWorkspace(page, hint = '5915') {
  await closeAime(page)
  const tablist = page.getByRole('tablist', { name: /Workspace sections/i })
  const ok = await tablist.waitFor({ state: 'visible', timeout: 30000 }).then(() => true).catch(() => false)
  if (!ok) {
    log('workspace.tablist', 'FAIL', `no workbench tabs; url=${page.url()}`)
    return false
  }
  if (hint) {
    await page.getByText(hint, { exact: false }).first().waitFor({ timeout: 15000 }).catch(() => {})
  }
  return true
}

async function waitSettled(page, ms = 280) {
  await page.waitForTimeout(ms)
  await page.waitForLoadState('domcontentloaded', { timeout: 8000 }).catch(() => {})
}

async function gotoPath(page, pathName) {
  const url = /^https?:\/\//i.test(pathName) ? pathName : `${APP}${pathName}`
  await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 45000 })
  await waitSettled(page, 350)
  await dismissOverlays(page)
}

async function expectVisible(page, locator, id, detailsOk = '') {
  const ok = await locator.first().isVisible({ timeout: 9000 }).catch(() => false)
  log(id, ok ? 'PASS' : 'FAIL', ok ? detailsOk : `not visible; url=${page.url()}`)
  return ok
}

async function dump(page, name) {
  const text = await bodyText(page)
  writeFileSync(path.join(OUT, `${name}.txt`), `${page.url()}\n\n${text}`)
  return text
}

function logForbidden(id, text) {
  const hits = scanForbidden(text)
  log(id, hits.length ? 'FAIL' : 'PASS', hits.length ? hits.join(', ') : 'no forbidden copy')
}

async function login(page) {
  await gotoPath(page, '/login')
  const email = page.locator('#login-email')
  await email.waitFor({ state: 'visible', timeout: 15000 })
  await email.fill(EMAIL)
  await page.locator('#login-password').fill(PASSWORD)
  await page.getByRole('button', { name: /sign in/i }).click()
  await page.waitForURL((u) => !u.pathname.includes('/login'), { timeout: 25000 }).catch(() => {})
  await waitSettled(page, 700)
  await dismissOverlays(page)
  const onLogin = page.url().includes('/login')
  if (onLogin) {
    const alert = await page.locator('[role="alert"]').innerText().catch(() => '')
    log('login', 'FAIL', alert || page.url())
    return false
  }
  log('login', 'PASS', page.url())
  return true
}

async function closeDialog(page) {
  const dlg = modal(page).first()
  if (!(await dlg.isVisible({ timeout: 400 }).catch(() => false))) return
  const cancel = dlg.getByRole('button', { name: /^(Cancel|Close|Not now|Got it)$/i }).first()
  if (await cancel.isVisible({ timeout: 400 }).catch(() => false)) {
    await cancel.click().catch(() => {})
  } else {
    await page.keyboard.press('Escape').catch(() => {})
  }
  await page.waitForTimeout(200)
}

async function run() {
  const browser = await chromium.launch({
    channel: CHANNEL,
    headless: !HEADED,
    args: [
      '--disable-gpu',
      '--disable-dev-shm-usage',
      '--disable-extensions',
      '--disable-background-networking',
      '--disable-sync',
      '--mute-audio',
      '--renderer-process-limit=1',
      '--js-flags=--max-old-space-size=192',
    ],
  })
  const context = await browser.newContext({
    viewport: { width: 1280, height: 900 },
    deviceScaleFactor: 1,
  })
  const page = await context.newPage()
  page.setDefaultTimeout(12000)
  page.on('console', (msg) => {
    if (msg.type() === 'error') consoleErrors.push(msg.text())
  })
  page.on('pageerror', (err) => pageErrors.push(err.message))
  page.on('response', (res) => {
    const url = res.url()
    if (!/\/api\/v1\//.test(url)) return
    if (res.status() >= 400) failedRequests.push(`${res.status()} ${url}`)
  })

  try {
    // ── Feature 7 register (logged out) ────────────────────────────────
    await gotoPath(page, '/register')
    const reg = await bodyText(page)
    await expectVisible(page, page.getByText('How should Aime start?'), 'f7.register.legend')
    await expectVisible(page, page.getByRole('button', { name: /^Manual/i }), 'f7.register.manual')
    await expectVisible(page, page.getByRole('button', { name: /^Assisted/i }), 'f7.register.assisted')
    await expectVisible(page, page.getByRole('button', { name: /^Autopilot/i }), 'f7.register.autopilot')
    log(
      'f7.register.manual_promise',
      /AI suggests\. You click to apply anything/i.test(reg) ? 'PASS' : 'FAIL',
    )
    log(
      'f7.register.assisted_tap',
      /you tap Send/i.test(reg) ? 'PASS' : 'FAIL',
    )
    log(
      'f7.register.autopilot_no_tap',
      /No tap/i.test(reg) ? 'PASS' : 'FAIL',
    )
    logForbidden('f7.register.forbidden', reg)

    if (!(await login(page))) return

    // ── Feature 1 connections ──────────────────────────────────────────
    await gotoPath(page, '/settings/connections')
    const conn = await dump(page, 'f1_connections')
    await expectVisible(
      page,
      page.getByRole('heading', { name: /Email & E-signature/i }),
      'f1.title',
    )
    const mailboxConnected = /\bDisconnect\b/.test(conn)
    log(
      'f1.this_user_mailbox',
      mailboxConnected ? 'PASS' : 'SKIP',
      mailboxConnected
        ? 'Gmail or Outlook shows Disconnect for this user'
        : 'this user shows Connect only — Overnight census can still count other users. Jake/Audri must connect their own mailbox before Send tests',
    )
    const testBtn = page.getByRole('button', { name: /Test connection/i }).first()
    if (await testBtn.isVisible({ timeout: 2000 }).catch(() => false)) {
      await testBtn.click()
      await page.waitForTimeout(2500)
      log('f1.test_connection', 'PASS', 'clicked Test connection')
    } else {
      log(
        'f1.test_connection',
        mailboxConnected ? 'FAIL' : 'SKIP',
        'Test connection only appears after a mailbox is connected',
      )
    }
    if (mailboxConnected) {
      await expectVisible(page, page.getByRole('button', { name: /Disconnect/i }).first(), 'f1.disconnect_visible')
    } else {
      log('f1.disconnect_visible', 'SKIP', 'no mailbox on this user; Connect is the live control')
    }
    logForbidden('f1.forbidden', conn)

    // ── Feature 2 How it runs + chip ───────────────────────────────────
    let holdStatus = true
    await page.route('**/api/v1/automation/status**', async (route) => {
      if (holdStatus) await new Promise((r) => setTimeout(r, 3500))
      await route.continue()
    })
    await page.goto(`${APP}/admin/confidence`, { waitUntil: 'domcontentloaded', timeout: 45000 })
    const chipEarly = page.getByText(/Checking automation|Automation active|Automation has stopped|Automation is not running/i).first()
    await chipEarly.waitFor({ state: 'visible', timeout: 8000 }).catch(() => {})
    const earlyLabel = ((await chipEarly.innerText().catch(() => '')) || '').replace(/\s+/g, ' ')
    log(
      'f2.chip_loading',
      /Checking automation/i.test(earlyLabel) && !/has stopped/i.test(earlyLabel)
        ? 'PASS'
        : /Automation has stopped/i.test(earlyLabel)
          ? 'FAIL'
          : 'FAIL',
      earlyLabel || 'chip missing on first paint',
    )
    holdStatus = false
    await page.waitForTimeout(4500)
    await dismissOverlays(page)
    const laterLabel = ((await chipEarly.innerText().catch(() => '')) || '').replace(/\s+/g, ' ')
    log(
      'f2.chip_settled',
      /Automation active/i.test(laterLabel) ? 'PASS' : 'FAIL',
      laterLabel,
    )

    const how = await dump(page, 'f2_how_it_runs')
    await expectVisible(page, page.getByRole('button', { name: /How it runs/i }).first(), 'f2.nav_how')
    log('f2.card.manual', /AI suggests\. You click to apply anything/i.test(how) ? 'PASS' : 'FAIL')
    log('f2.card.assisted', /Named letters are drafted — you tap Send/i.test(how) ? 'PASS' : 'FAIL')
    log('f2.card.autopilot', /Authorized letters send when confidence is high enough\. No tap/i.test(how) ? 'PASS' : 'FAIL')
    log('f2.table.welcome_never_auto', /Never auto/i.test(how) ? 'PASS' : 'FAIL')
    log('f2.table.sends_without_tap', /Sends without a tap/i.test(how) ? 'PASS' : 'FAIL')
    log('f2.workspace_default', /Autopilot/i.test(how) ? 'PASS' : 'FAIL', 'expect Autopilot selected on this tenant')
    logForbidden('f2.forbidden', how)

    // ── Feature 3 Overnight ────────────────────────────────────────────
    log('f3.overnight_title', /Overnight/i.test(how) ? 'PASS' : 'FAIL')
    log('f3.last_run', /Last run/i.test(how) ? 'PASS' : 'FAIL')
    log('f3.last_draft_sweep', /Last draft sweep/i.test(how) ? 'PASS' : 'FAIL')
    log('f3.hourly', /Hourly automation/i.test(how) ? 'PASS' : 'FAIL')
    log('f3.named_letters', /Named letters/i.test(how) ? 'PASS' : 'FAIL')
    log('f3.aime_signature', /Aime signature/i.test(how) ? 'PASS' : 'FAIL')
    log('f3.inspection', /Inspection reminders/i.test(how) ? 'PASS' : 'FAIL')
    log(
      'f3.inspection_current',
      /Inspection reminders[\s\S]{0,400}Allowed|Paused/i.test(how) ? 'PASS' : 'FAIL',
      'live switch may be Allowed on this tenant — not a Fail',
    )
    log('f3.always_true', /Always true/i.test(how) ? 'PASS' : 'FAIL')
    log('f3.always.deadlines', /Deadlines never move themselves/i.test(how) ? 'PASS' : 'FAIL')
    log('f3.always.wire', /Wire and funds mail is never drafted/i.test(how) ? 'PASS' : 'FAIL')
    log('f3.always.waives', /Waives, legal calls, and packet release stay human/i.test(how) ? 'PASS' : 'FAIL')
    log(
      'f3.mailbox_census',
      /Mailboxes · \d+ healthy \/ \d+ connected/i.test(how) ? 'PASS' : 'FAIL',
      'workspace census, not this-user Email & E-signature',
    )
    if (!mailboxConnected && /Mailboxes · [1-9]/i.test(how)) {
      noteGuideline(
        'Feature 1 vs 3: Overnight Mailboxes is workspace census. This admin can have 0 personal mailboxes while Overnight shows connected inboxes for other users.',
      )
    }

    // ── Feature 4 Preview / Run (cancel) ───────────────────────────────
    await closeAime(page)
    const previewBtn = page.getByRole('button', { name: /Preview next run/i })
    const previewClicked = await clickVisible(previewBtn, 'f4.preview_button')
    if (previewClicked) {
      const previewDlg = modal(page).first()
      const previewOk = await previewDlg.waitFor({ state: 'visible', timeout: 60000 }).then(() => true).catch(() => false)
      if (previewOk) {
        const ptxt = await previewDlg.innerText()
        writeFileSync(path.join(OUT, 'f4_preview.txt'), ptxt)
        log(
          'f4.preview_dialog',
          /This run would send/i.test(ptxt) ? 'PASS' : 'FAIL',
          ptxt.slice(0, 500),
        )
        log('f4.preview_got_it', /Got it/i.test(ptxt) ? 'PASS' : 'FAIL')
        await previewDlg.getByRole('button', { name: /Got it/i }).click().catch(() => {})
        await page.waitForTimeout(300)
      } else {
        log('f4.preview_dialog', 'FAIL', 'alertdialog never opened after Preview')
      }
    }

    await expectVisible(page, page.getByRole('button', { name: /Draft due emails/i }), 'f4.draft_button')
    if (DO_DRAFT) {
      await clickVisible(page.getByRole('button', { name: /Draft due emails/i }), 'f4.draft_click')
      const toast = await page.getByText(/Draft sweep ran|Nothing was sent|Prepared/i).first()
        .isVisible({ timeout: 90000 })
        .catch(() => false)
      log('f4.draft_sweep', toast ? 'PASS' : 'FAIL', toast ? 'toast seen' : 'no toast in 90s')
    } else {
      log('f4.draft_sweep', 'SKIP', 'QA_DRAFT not set — Draft due emails writes drafts; skipped to keep this pass short')
    }

    const runBtn = page.getByRole('button', { name: /Run AI tasks \(sends deal email\)/i })
    const runClicked = await clickVisible(runBtn, 'f4.run_button')
    if (runClicked) {
      const runDlg = modal(page).first()
      const runOk = await runDlg.waitFor({ state: 'visible', timeout: 60000 }).then(() => true).catch(() => false)
      if (runOk) {
        const rtxt = await runDlg.innerText()
        writeFileSync(path.join(OUT, 'f4_run_confirm.txt'), rtxt)
        log(
          'f4.run_confirm_honesty',
          /real emails to real people/i.test(rtxt) ? 'PASS' : 'FAIL',
          rtxt.slice(0, 500),
        )
        await runDlg.getByRole('button', { name: /Cancel/i }).click()
        await page.waitForTimeout(250)
        log('f4.run_cancelled', 'PASS', 'did not confirm send')
      } else {
        log('f4.run_confirm_honesty', 'FAIL', 'confirm never opened')
      }
    }
    await expectVisible(page, page.getByRole('button', { name: /Send me my digest/i }), 'f4.digest_button')

    // ── Feature 25 Fine-tune has no send console ───────────────────────
    for (const label of ['AI model', 'Email replies', 'Automation rules', 'Confidence gates']) {
      const nav = page.getByRole('button', { name: new RegExp(`^${label}$`, 'i') }).first()
      if (await nav.isVisible({ timeout: 1500 }).catch(() => false)) {
        await nav.click()
        if (label === 'Automation rules') {
          await page
            .getByText(/Ask me|Never automatic|Add a contact|Always approve/i)
            .first()
            .waitFor({ timeout: 15000 })
            .catch(() => {})
          await waitSettled(page, 800)
        } else {
          await waitSettled(page, 400)
        }
        const t = await bodyText(page)
        if (label === 'Automation rules') await dump(page, 'f25_automation_rules')
        log(
          `f25.finetune.${label.replace(/\s+/g, '_').toLowerCase()}`,
          /Preview next run|Preview next tick|Run AI tasks/i.test(t) ? 'FAIL' : 'PASS',
          /Preview next run|Preview next tick|Run AI tasks/i.test(t) ? 'send controls leaked into Fine-tune' : 'no send console',
        )
        if (label === 'Automation rules') {
          log(
            'f25.never_automatic',
            /Never automatic/i.test(t) ? 'PASS' : 'FAIL',
            /Never automatic/i.test(t) ? 'heading after rules loaded' : t.slice(0, 400),
          )
        }
      } else {
        log(`f25.finetune.${label.replace(/\s+/g, '_').toLowerCase()}`, 'FAIL', 'nav missing')
      }
    }

    // ── Feature 5 Needs You ────────────────────────────────────────────
    await gotoPath(page, '/needs-you')
    await page.getByText(/waiting ·|Nothing needs you|Overnight prep ran/i).first()
      .waitFor({ timeout: 30000 })
      .catch(() => {})
    const ny = await dump(page, 'f5_needs_you')
    await expectVisible(page, page.getByRole('heading', { name: /Needs You/i }), 'f5.title')
    log('f5.breadcrumb', /Workflow/.test(ny) && /Needs You/.test(ny) ? 'PASS' : 'FAIL')
    log('f5.pill', /\d+ waiting/i.test(ny) ? 'PASS' : 'FAIL', 'count pill should leave Loading')
    for (const tile of ['Ready to send', 'To approve', 'To review', 'To decide', 'To handle']) {
      await expectVisible(
        page,
        page.getByRole('button', { name: new RegExp(`${tile} items`, 'i') }).first(),
        `f5.tile.${tile.replace(/\s+/g, '_')}`,
      )
    }
    log(
      'f5.intro',
      /These items still need a person|Overnight prep ran/i.test(ny) ? 'PASS' : 'FAIL',
    )
    log('f5.no_run_button', /Run AI tasks/i.test(ny) ? 'FAIL' : 'PASS')
    await clickVisible(page.getByRole('button', { name: /To handle items/i }), 'f5.to_handle_click')
    await waitSettled(page, 400)
    const missingDocOrderTitle = page
      .locator('div')
      .filter({ hasText: /Order Title/i })
      .filter({ hasText: /purchase agreement attached|Upload document/i })
      .getByText('Order Title', { exact: true })
      .first()
    const overdueRetry = page.getByRole('button', { name: /Use today's date and retry/i }).first()
    if (await missingDocOrderTitle.isVisible({ timeout: 5000 }).catch(() => false)) {
      await missingDocOrderTitle.click()
      await waitSettled(page, 400)
    } else if (await page.getByText('Order Title').first().isVisible({ timeout: 2000 }).catch(() => false)) {
      await page.getByText('Order Title').first().click()
      await waitSettled(page, 400)
    }
    const nyHandle = await bodyText(page)
    const hasUpload = /Upload document/i.test(nyHandle)
    const hasOverdueRetry = /Use today's date and retry/i.test(nyHandle)
    log(
      'f5.to_handle.upload',
      hasUpload || hasOverdueRetry ? 'PASS' : 'FAIL',
      hasUpload
        ? 'missing-doc Order Title shows Upload document'
        : hasOverdueRetry
          ? "To handle Order Title is overdue (Use today's date and retry) — expected when the file already has a contract"
          : 'no Order Title upload or overdue-retry path',
    )
    const missingDocCard = page
      .locator('div.bg-white')
      .filter({ hasText: /Order Title|Upload document/i })
      .filter({ has: page.getByRole('link', { name: /Upload document/i }) })
      .first()
    if (await missingDocCard.isVisible({ timeout: 2500 }).catch(() => false)) {
      const giveBackOnMissing = missingDocCard.getByRole('button', {
        name: /^Give this back to the AI$/i,
      })
      const stillThere = await giveBackOnMissing.isVisible({ timeout: 800 }).catch(() => false)
      log(
        'f5.to_handle.give_back_not_on_missing_doc',
        stillThere ? 'FAIL' : 'PASS',
        stillThere
          ? 'Give-back still on a missing-document card'
          : 'Upload document only; Give-back hidden',
      )
    } else {
      log(
        'f5.to_handle.give_back_not_on_missing_doc',
        /Upload document/i.test(nyHandle) ? 'PASS' : 'SKIP',
        'no scoped missing-doc card; fallback is Upload document present',
      )
    }
    const tryNow = page.getByRole('button', { name: /Try now \(this deal only\)/i }).first()
    log(
      'f5.try_now_admin',
      (await tryNow.isVisible({ timeout: 4000 }).catch(() => false)) ? 'PASS' : 'FAIL',
      'Admin should see Try now on a blocked card',
    )
    const sendAll = page.getByRole('button', { name: /Send all ready/i }).first()
    if (await sendAll.isEnabled().catch(() => false)) {
      await sendAll.click()
      const dlg = modal(page).first()
      const opened = await dlg.waitFor({ state: 'visible', timeout: 8000 }).then(() => true).catch(() => false)
      if (opened) {
        const stxt = await dlg.innerText()
        writeFileSync(path.join(OUT, 'f5_send_all.txt'), stxt)
        log('f5.send_all_confirm', 'PASS', stxt.slice(0, 400))
        await dlg.getByRole('button', { name: /Cancel/i }).click()
        log('f5.send_all_cancelled', 'PASS')
      } else {
        log('f5.send_all_confirm', 'FAIL', 'no confirm')
      }
    } else {
      log('f5.send_all_confirm', 'SKIP', 'Send all ready disabled or zero ready')
    }
    const titleWork = page.getByText('Title Work Completed').first()
    if (await titleWork.isVisible({ timeout: 4000 }).catch(() => false)) {
      await titleWork.click()
      await waitSettled(page, 400)
    }
    const addContact = page.getByRole('link', { name: /^Add contact$/i }).first()
    if (await addContact.isVisible({ timeout: 2500 }).catch(() => false)) {
      const href = (await addContact.getAttribute('href')) || ''
      log(
        'f5.add_contact_href',
        /tab=contacts/i.test(href) && !/tab=people/i.test(href) ? 'PASS' : 'FAIL',
        href,
      )
    } else {
      log('f5.add_contact_href', 'SKIP', 'no Add contact row in the current Needs You slice')
    }
    await clickVisible(page.getByRole('button', { name: /Ready to send items/i }), 'f5.ready_click')
    await waitSettled(page, 400)
    const readyText = await bodyText(page)
    writeFileSync(path.join(OUT, 'f5_ready_to_send.txt'), readyText)
    const giveBackOnReady = page.getByRole('button', { name: /^Give this back to the AI$/i })
    const giveBackReadyCount = await giveBackOnReady.count()
    log(
      'f16.give_back_absent_on_ready_to_send',
      giveBackReadyCount === 0 ? 'PASS' : 'FAIL',
      giveBackReadyCount === 0
        ? 'no Give-back on Ready to send (Assisted letters wait for Send)'
        : `${giveBackReadyCount} Give-back button(s) on Ready to send`,
    )
    logForbidden('f5.forbidden', ny)

    // ── Feature 21 Intelligence Email ──────────────────────────────────
    await gotoPath(page, '/ai-emails')
    const emails = await dump(page, 'f21_ai_emails')
    await expectVisible(page, page.getByRole('heading', { name: /^Email$/i }), 'f21.title_email')
    log('f21.not_ai_emails_title', /AI Emails/i.test(emails.split('\n').slice(0, 12).join('\n')) ? 'FAIL' : 'PASS')
    log('f21.breadcrumb', /Intelligence/.test(emails) ? 'PASS' : 'FAIL')
    logForbidden('f21.forbidden', emails)

    // ── Feature 6 Fast intake (upload step must NOT show it) ───────────
    await gotoPath(page, '/transactions/new')
    const wiz = await dump(page, 'f6_wizard_start')
    log(
      'f6.no_fast_intake_on_upload',
      /✦ Fast intake/i.test(wiz) ? 'FAIL' : 'PASS',
      'Fast intake must not appear before Confirm Details',
    )
    log('f6.skip_confirm_details', 'SKIP', 'no contract upload this pass (RAM); Confirm Details banner not exercised')

    // Cash appraisal field lives on Contract Details when has_mortgage is false.
    log(
      'f14.cash_appraisal_field',
      'SKIP',
      'no cash file in this tenant; wizard Contract Details not reached without a contract',
    )

    // ── Features 8–13 workspace ────────────────────────────────────────
    await gotoPath(page, `/transactions/${DEAL}`)
    const wsReady = await waitForWorkspace(page, '5915')
    const ws = await dump(page, 'f8_workspace')
    if (!wsReady) {
      log('f8.posture_chip', 'FAIL', 'workspace never painted')
    } else {
    await expectVisible(
      page,
      page.getByRole('button', { name: /Automation posture for this deal/i }),
      'f8.posture_chip',
    )
    const postureBtn = page.getByRole('button', { name: /Automation posture for this deal/i })
    await postureBtn.click()
    await page.waitForTimeout(400)
    const menu = await bodyText(page)
    log(
      'f8.caption_in_menu',
      /Authorized letters send without a tap when confidence is high enough/i.test(menu)
        ? 'PASS'
        : 'FAIL',
      'captions live inside the posture menu, not under the chip',
    )
    log(
      'f8.assisted_caption',
      /Named letters are drafted — you tap Send/i.test(menu) ? 'PASS' : 'FAIL',
    )
    log(
      'f8.manual_caption',
      /Named letters wait until you switch this deal off Manual/i.test(menu) ? 'PASS' : 'FAIL',
    )
    log(
      'f8.use_workspace_default',
      /Use workspace default/i.test(menu) ? 'PASS' : 'FAIL',
    )
    noteGuideline(
      'Feature 8: posture captions are inside the header menu, not printed under the chip. Testers must open the Autopilot/Assisted control.',
    )
    await page.keyboard.press('Escape').catch(() => {})
    logForbidden('f8.forbidden', ws)
    }

    // Feature 9 Contacts — workbench tab, not sidebar directory
    await gotoPath(page, `/transactions/${DEAL}?tab=contacts`)
    await waitForWorkspace(page, '5915')
    const closeQa = page.getByRole('button', { name: /Close client Q&A/i })
    if (await closeQa.isVisible({ timeout: 800 }).catch(() => false)) {
      await closeQa.click().catch(() => {})
    }
    const retiredPeopleTab = page.getByRole('tab', { name: /^People$/i })
    const retiredPeopleVisible = await retiredPeopleTab.isVisible({ timeout: 800 }).catch(() => false)
    log('f9.no_retired_tab', retiredPeopleVisible ? 'FAIL' : 'PASS', retiredPeopleVisible ? 'retired People tab still visible' : 'retired People tab absent')
    await expectVisible(page, page.getByRole('tab', { name: /^Contacts$/i }), 'f9.contacts_tab')
    await page.getByRole('button', { name: /Add buyer/i }).waitFor({ state: 'visible', timeout: 20000 }).catch(() => {})
    const contacts = await dump(page, 'f9_contacts')
    log('f9.not_directory', /Everyone you work with/i.test(contacts) ? 'FAIL' : 'PASS', 'must not be sidebar Contacts directory')
    log('f9.heading', /✦ PARTIES/i.test(contacts) || /✦ Parties/i.test(contacts) ? 'PASS' : 'FAIL')
    log('f9.kicker', /Parties/i.test(contacts) ? 'PASS' : 'FAIL')
    log('f9.groups.buyer', /Add buyer/i.test(contacts) || /No buyer on file/i.test(contacts) ? 'PASS' : 'FAIL')
    log('f9.groups.seller', /Add seller/i.test(contacts) || /No seller on file/i.test(contacts) ? 'PASS' : 'FAIL')
    log('f9.groups.agents', /Add agent/i.test(contacts) || /No co-op agent on file/i.test(contacts) ? 'PASS' : 'FAIL')
    log('f9.groups.lender', /Add loan officer/i.test(contacts) || /No lender contact on file/i.test(contacts) ? 'PASS' : 'FAIL')
    log('f9.groups.title', /Add title contact/i.test(contacts) || /No title contact on file/i.test(contacts) ? 'PASS' : 'FAIL')
    log(
      'f9.add_buttons',
      /Add buyer/i.test(contacts) && /Add agent/i.test(contacts) ? 'PASS' : 'FAIL',
    )
    log(
      'f9.email_not_printed',
      /info@titlecompany\.com/i.test(contacts) ? 'FAIL' : 'PASS',
    )
    logForbidden('f9.forbidden', contacts)

    await gotoPath(page, `/transactions/${DEAL}?tab=people`)
    await waitForWorkspace(page, '5915')
    const aliased = await dump(page, 'f9_legacy_people_alias')
    const contactsTab = page.getByRole('tab', { name: /^Contacts$/i })
    const contactsSelected = await contactsTab.getAttribute('aria-selected').catch(() => null)
    log(
      'f9.legacy_people_alias',
      contactsSelected === 'true' && /Add buyer|✦ PARTIES|✦ Parties/i.test(aliased) ? 'PASS' : 'FAIL',
      `aria-selected=${contactsSelected}`,
    )

    // Feature 10 Email tab
    await gotoPath(page, `/transactions/${DEAL}?tab=email`)
    await waitForWorkspace(page, '5915')
    const em = await dump(page, 'f10_email_tab')
    if (/Nothing sends until you tap Send/i.test(em)) {
      log(
        'f10.sentence',
        /Nothing sends until you tap Send\. On Autopilot, named welcome \/ title \/ inspection-reminder letters may already have gone out on their own\. On Assisted they wait here for Send/i.test(
          em,
        )
          ? 'PASS'
          : 'FAIL',
        em.slice(0, 400),
      )
      await expectVisible(page, page.getByRole('tab', { name: /^Outbox/i }), 'f10.outbox')
      await expectVisible(page, page.getByRole('tab', { name: /^Sent/i }), 'f10.sent')
      await expectVisible(page, page.getByRole('tab', { name: /^Inbox/i }), 'f10.inbox')
      logForbidden('f10.forbidden', em)
    } else {
      log('f10.sentence', 'FAIL', `Email tab missing copy; url=${page.url()}`)
      log('f10.outbox', 'FAIL', 'not on Email tab')
      log('f10.sent', 'FAIL', 'not on Email tab')
      log('f10.inbox', 'FAIL', 'not on Email tab')
    }

    // Feature 11–12 Tasks / Complete this task / CD omit
    await gotoPath(page, `/transactions/${DEAL}?tab=tasks`)
    await waitForWorkspace(page, '5915')
    await page.getByText(/Welcome|Appraisal|Order Title|Closing Information/i).first()
      .waitFor({ timeout: 25000 })
      .catch(() => {})
    const tasks = await dump(page, 'f11_tasks')
    const utilityCard = page.locator('li').filter({ hasText: 'Deliver Utility Info' }).first()
    if (await utilityCard.isVisible({ timeout: 2500 }).catch(() => false)) {
      const giveBackOnUtility = utilityCard.getByRole('button', {
        name: /^Give this back to the AI$/i,
      })
      const stillThere = await giveBackOnUtility.isVisible({ timeout: 800 }).catch(() => false)
      log(
        'f16.give_back_hidden_on_missing_doc_task',
        stillThere ? 'FAIL' : 'PASS',
        stillThere
          ? 'Give-back still on Deliver Utility Info (missing attachment)'
          : 'Give-back hidden on missing-document task after deploy',
      )
    } else {
      log('f16.give_back_hidden_on_missing_doc_task', 'SKIP', 'Deliver Utility Info not on this file')
    }
    const welcomeCard = page.locator('li').filter({ hasText: /Buyer Welcome/i }).first()
    if (await welcomeCard.isVisible({ timeout: 1500 }).catch(() => false)) {
      const giveBackOnWelcome = welcomeCard.getByRole('button', {
        name: /^Give this back to the AI$/i,
      })
      const stillThere = await giveBackOnWelcome.isVisible({ timeout: 600 }).catch(() => false)
      log(
        'f16.give_back_hidden_on_assisted_welcome',
        stillThere ? 'FAIL' : 'PASS',
        stillThere
          ? 'Give-back still on Buyer Welcome'
          : 'no Give-back on Buyer Welcome',
      )
    } else {
      log('f16.give_back_hidden_on_assisted_welcome', 'SKIP', 'Buyer Welcome row not visible')
    }
    const closingRow = page.getByText(CLOSING_TASK, { exact: false }).first()
    const closingVisible = await closingRow.isVisible({ timeout: 5000 }).catch(() => false)
    if (!closingVisible) {
      log('f11.closing_row', 'SKIP', `${CLOSING_TASK} not visible on this file (may be Completed/hidden)`)
      log('f12.cd_omit', 'SKIP', 'no closing-information dialog this pass')
    } else {
      log('f11.closing_row', 'PASS')
      await closingRow.click()
      await page.waitForTimeout(500)
      const dlgAfterRow = await modal(page).first().isVisible({ timeout: 600 }).catch(() => false)
      log('f11.row_click_expands_only', dlgAfterRow ? 'FAIL' : 'PASS', dlgAfterRow ? 'dialog opened on row click' : 'no dialog')
      const kebab = page.getByRole('button', { name: new RegExp(`Actions for ${CLOSING_TASK}`, 'i') }).first()
      if (await kebab.isVisible({ timeout: 3000 }).catch(() => false)) {
        await kebab.click()
        const emailItem = page.getByRole('menuitem', { name: /Email transaction party/i })
        await expectVisible(page, emailItem, 'f11.kebab_email')
        await emailItem.click()
        const taskDlg = modal(page).first()
        const opened = await taskDlg.waitFor({ state: 'visible', timeout: 25000 }).then(() => true).catch(() => false)
        if (opened) {
          await page.waitForTimeout(2500)
          const dtxt = await taskDlg.innerText()
          writeFileSync(path.join(OUT, 'f11_complete_this_task.txt'), dtxt)
          log('f11.title', /Complete this task/i.test(dtxt) ? 'PASS' : 'FAIL')
          const box = await taskDlg.boundingBox()
          log(
            'f11.dialog_has_height',
            box && box.height > 200 ? 'PASS' : 'FAIL',
            box ? `h=${Math.round(box.height)}` : 'no box',
          )
          log(
            'f12.cd_omit',
            /Closing Disclosure/i.test(dtxt) ? 'FAIL' : 'PASS',
            /Closing Disclosure/i.test(dtxt) ? 'CD listed on closing-information plan' : 'no CD on plan',
          )
          logForbidden('f11.forbidden', dtxt)
          await page.keyboard.press('Escape').catch(() => {})
          await closeDialog(page)
        } else {
          log('f11.title', 'FAIL', 'Complete this task did not open')
          log('f12.cd_omit', 'FAIL', 'dialog missing')
        }
      } else {
        log('f11.kebab_email', 'FAIL', 'kebab not found')
        log('f12.cd_omit', 'SKIP', 'could not open email plan')
      }
    }

    // Feature 13 status copy — cancel
    const activeChip = page.locator('button').filter({ hasText: /^Active$/ }).first()
    if (await activeChip.isVisible({ timeout: 3000 }).catch(() => false)) {
      await activeChip.click()
      await page.waitForTimeout(300)
      const completedItem = page.getByRole('menuitem', { name: /^Completed$/ })
      if (await completedItem.isVisible({ timeout: 2000 }).catch(() => false)) {
        await completedItem.click()
        const dlg = modal(page).first()
        const opened = await dlg.waitFor({ state: 'visible', timeout: 8000 }).then(() => true).catch(() => false)
        if (opened) {
          const t = await dlg.innerText()
          writeFileSync(path.join(OUT, 'f13_completed.txt'), t)
          log(
            'f13.completed_copy',
            /Closing day is not the end of the file/i.test(t) ? 'PASS' : 'FAIL',
            t.slice(0, 400),
          )
          log('f13.completed_title', /Change status to Completed/i.test(t) ? 'PASS' : 'FAIL')
          await dlg.getByRole('button', { name: /Cancel/i }).click().catch(() => page.keyboard.press('Escape'))
        } else {
          log('f13.completed_copy', 'FAIL', 'dialog missing')
        }
      } else {
        log('f13.completed_copy', 'FAIL', 'Completed menu item missing')
      }
      await page.waitForTimeout(300)
      if (await activeChip.isVisible({ timeout: 2000 }).catch(() => false)) await activeChip.click()
      const termItem = page.getByRole('menuitem', { name: /^Terminated$/ })
      if (await termItem.isVisible({ timeout: 2000 }).catch(() => false)) {
        await termItem.click()
        const dlg = modal(page).first()
        const opened = await dlg.waitFor({ state: 'visible', timeout: 8000 }).then(() => true).catch(() => false)
        if (opened) {
          const t = await dlg.innerText()
          writeFileSync(path.join(OUT, 'f13_terminated.txt'), t)
          log(
            'f13.terminated_copy',
            /The deal fell through/i.test(t) ? 'PASS' : 'FAIL',
            t.slice(0, 400),
          )
          await dlg.getByRole('button', { name: /Cancel/i }).click().catch(() => page.keyboard.press('Escape'))
        } else {
          log('f13.terminated_copy', 'FAIL', 'dialog missing')
        }
      } else {
        log('f13.terminated_copy', 'FAIL', 'Terminated menu item missing')
      }
    } else {
      log('f13.completed_copy', 'FAIL', 'Active status chip not found')
    }

    await gotoPath(page, '/transactions/all?tab=Terminated')
    const termList = await dump(page, 'f13_terminated_list')
    log('f13.terminated_tab', /Terminated/i.test(termList) ? 'PASS' : 'FAIL')
    log(
      'f13.closed_empty_hint_optional',
      'SKIP',
      'Closed empty hint checked only if Closed tab opened',
    )
    await gotoPath(page, '/transactions/all?tab=Closed')
    const closed = await bodyText(page)
    log(
      'f13.closed_hint',
      /Terminated, not Closed/i.test(closed) || /Closed/i.test(closed) ? 'PASS' : 'FAIL',
      /Terminated, not Closed/i.test(closed) ? 'empty hint present' : 'Closed tab opened; hint may only show when empty',
    )

    await gotoPath(page, '/')
    await page.getByRole('link', { name: /^Terminated$/i }).first().waitFor({ timeout: 25000 }).catch(() => {})
    const dash = await dump(page, 'f13_admin_dash')
    log('f13.admin_terminated_tile', /Terminated/i.test(dash) ? 'PASS' : 'FAIL')

    // ── Feature 24 Ask AI — open, do not approve ───────────────────────
    await gotoPath(page, `/transactions/${DEAL}`)
    await waitForWorkspace(page, '5915')
    const ask = page.getByRole('button', { name: /^Ask AI$/i }).first()
    if (await ask.isVisible({ timeout: 4000 }).catch(() => false)) {
      await ask.click()
      const composer = page.locator('textarea').first()
      const ready = await composer.waitFor({ state: 'visible', timeout: 8000 }).then(() => true).catch(() => false)
      if (ready) {
        await composer.fill('Change the closing date on this file to September 15, 2026.')
        const send = page.getByRole('button', { name: /Send|Ask/i }).last()
        if (await send.isVisible({ timeout: 2000 }).catch(() => false)) {
          await send.click().catch(() => {})
        } else {
          await composer.press('Enter').catch(() => {})
        }
        const proposal = await page.getByRole('button', { name: /^Dismiss$/i }).isVisible({ timeout: 40000 }).catch(() => false)
        if (proposal) {
          log('f24.proposal', 'PASS', 'Dismiss visible')
          await page.getByRole('button', { name: /^Dismiss$/i }).click()
          log('f24.dismissed', 'PASS', 'did not Approve')
        } else {
          log('f24.proposal', 'SKIP', 'no Dismiss in 40s — model slow or gated')
        }
      } else {
        log('f24.proposal', 'SKIP', 'Ask AI composer not visible')
      }
    } else {
      log('f24.proposal', 'SKIP', 'Ask AI header button not visible at this viewport')
    }

    // ── Feature 25 notifications ───────────────────────────────────────
    await gotoPath(page, '/settings/notifications')
    const notes = await dump(page, 'f25_notifications')
    await expectVisible(page, page.getByRole('heading', { name: /Notifications/i }), 'f25.notifications_title')
    log('f25.digest_independent', /digest/i.test(notes) ? 'PASS' : 'FAIL')

    // ── Skips that would send, disconnect, or create files ─────────────
    log('f15.manual_named_letters', 'SKIP', 'would pin a live Autopilot file Manual or create 200 Test Maple Ave')
    log('f16.assisted_send', 'SKIP', 'would Send to a live party inbox')
    log('f17.autopilot_run', 'SKIP', 'Run AI tasks would mail every Autopilot file in this workspace')
    log('f18.blank_email_file', 'SKIP', 'would create 400 Test Cedar St')
    log('f19.inspection_toggle', 'SKIP', 'would flip Inspection reminders on the live tenant')
    log('f20.disconnect', 'SKIP', 'would disconnect the platform-admin mailbox; OAuth reconnect is not headless-safe')
    log('f23.inbound_money', 'SKIP', 'needs a second mailbox to send inbound wire/banking mail')

    logForbidden('f26.workspace', await bodyText(page))
  } catch (err) {
    log('harness', 'FAIL', err.stack || err.message)
  } finally {
    const summary = {
      app: APP,
      email: EMAIL,
      deal: DEAL,
      pass: findings.filter((f) => f.result === 'PASS').length,
      fail: findings.filter((f) => f.result === 'FAIL').length,
      skip: findings.filter((f) => f.result === 'SKIP').length,
      findings,
      guidelineNotes,
      failedRequests: [...new Set(failedRequests)].slice(0, 40),
      pageErrors: pageErrors.slice(0, 20),
      consoleErrors: consoleErrors.slice(0, 20),
    }
    writeFileSync(path.join(OUT, 'summary.json'), JSON.stringify(summary, null, 2))
    console.log(
      `\nSUMMARY pass=${summary.pass} fail=${summary.fail} skip=${summary.skip} out=${OUT}`,
    )
    await context.close().catch(() => {})
    await browser.close().catch(() => {})
  }
}

run().catch((err) => {
  console.error(err)
  process.exit(1)
})
