"""Render CASA 1.3.3 write-up pages as portal-ready PNGs."""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

OUT = Path(r"c:\Projects\velvet-elves-data\casa_al1_evidence\m9\tac_images\1.3.3")
OUT.mkdir(parents=True, exist_ok=True)

W, H = 1400, 1800
MARGIN = 56
BG = (248, 248, 246)
INK = (24, 24, 24)
MUTED = (80, 80, 80)
RULE = (200, 80, 70)
OK = (20, 90, 50)
LINE = (220, 218, 214)
CODE_BG = (36, 36, 36)
CODE_FG = (230, 230, 226)


def font(size: int, bold: bool = False):
    name = "segoeuib.ttf" if bold else "segoeui.ttf"
    for p in (
        rf"C:\Windows\Fonts\{name}",
        r"C:\Windows\Fonts\arialbd.ttf" if bold else r"C:\Windows\Fonts\arial.ttf",
        r"C:\Windows\Fonts\calibri.ttf",
    ):
        if Path(p).exists():
            return ImageFont.truetype(p, size)
    return ImageFont.load_default()


def mono(size: int):
    for p in (r"C:\Windows\Fonts\consola.ttf", r"C:\Windows\Fonts\cour.ttf"):
        if Path(p).exists():
            return ImageFont.truetype(p, size)
    return font(size)


F_H = font(22, True)
F_SUB = font(14)
F_SEC = font(16, True)
F_BODY = font(15)
F_SMALL = font(13)
F_FOOT = font(12)
F_MONO = mono(14)


def wrap(draw, text, fnt, width):
    words = text.split()
    lines = []
    cur = ""
    for w in words:
        trial = f"{cur} {w}".strip()
        if draw.textlength(trial, font=fnt) <= width:
            cur = trial
        else:
            if cur:
                lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines or [""]


def new_page(title: str, page_no: int):
    im = Image.new("RGB", (W, H), BG)
    d = ImageDraw.Draw(im)
    d.rectangle((0, 0, W, 10), fill=RULE)
    d.text((MARGIN, 36), "Velvet Elves  |  ADA-CASA AL1 evidence", font=F_SUB, fill=MUTED)
    d.text((MARGIN, 64), title, font=F_H, fill=INK)
    d.text(
        (MARGIN, 98),
        "GCP 538509143953  |  production app.velvetelves.com  |  28 Aug 2026",
        font=F_SMALL,
        fill=MUTED,
    )
    d.line((MARGIN, 124, W - MARGIN, 124), fill=LINE, width=1)
    d.text((MARGIN, H - 42), f"Page {page_no} of 2", font=F_FOOT, fill=MUTED)
    d.text((W - MARGIN - 250, H - 42), "CASA_1_3_3_oob_random", font=F_FOOT, fill=MUTED)
    return im, d, 144


def paint(d, y, lines):
    max_w = W - 2 * MARGIN
    for text, fnt, color in lines:
        for part in wrap(d, text, fnt, max_w):
            d.text((MARGIN, y), part, font=fnt, fill=color)
            y += 22 if fnt is F_SMALL else 24
        y += 4
    return y


def page1():
    im, d, y = new_page("1.3.3 Out of band verifier is securely random", 1)
    y = paint(
        d,
        y,
        [
            (
                "Source: ADA Web App Test Guide v1.0 / ASVS 2.7.6.",
                F_SMALL,
                MUTED,
            ),
        ],
    )
    y += 8
    d.text((MARGIN, y), "1. External user authentication services", font=F_SEC, fill=INK)
    y += 32
    y = paint(
        d,
        y,
        [
            (
                "Supabase Auth (GoTrue) issues password-reset recovery emails, Email OTP, signup confirmation, and TOTP MFA secrets. It is not claimed as an ADA-approved identity provider. Google OAuth is not an email or SMS login verifier. Velvet Elves does not send SMS one-time codes.",
                F_BODY,
                INK,
            ),
        ],
    )
    y += 10
    d.text((MARGIN, y), "2. Password reset (vendor-generated)", font=F_SEC, fill=INK)
    y += 32
    y = paint(
        d,
        y,
        [
            (
                "POST /users/password-reset/request calls supabase.auth.reset_password_email. The API does not mint a reset code and does not store an OTP in application tables. Confirm uses the recovery token from the email (POST /users/password-reset/confirm).",
                F_BODY,
                INK,
            ),
            (
                "Auth Email OTP length is 8 digits (vendor dashboard). Recovery emails carry a hashed GoTrue token in the link, not a sequential number generated by Velvet Elves. Opening /reset-password without a valid token cannot set a password.",
                F_BODY,
                INK,
            ),
        ],
    )
    y += 10
    d.text((MARGIN, y), "3. Invite token (app-generated, CSPRNG)", font=F_SEC, fill=INK)
    y += 32
    y = paint(
        d,
        y,
        [
            (
                "InvitationRepository.create sets token = uuid.uuid4().hex (32 hex characters). CPython uuid.uuid4 draws from os.urandom. Invite lifetime and single-use are documented under 1.1.2 and 1.3.2.",
                F_BODY,
                INK,
            ),
        ],
    )
    y += 10
    d.text((MARGIN, y), "4. TOTP MFA", font=F_SEC, fill=INK)
    y += 32
    y = paint(
        d,
        y,
        [
            (
                "The TOTP shared secret is returned by GoTrue factor enrollment. Velvet Elves does not generate that secret. Authenticator codes use the standard 30-second RFC 6238 time step.",
                F_BODY,
                INK,
            ),
        ],
    )
    im.save(OUT / "CASA_1_3_3_page1.png", "PNG")
    print("wrote", OUT / "CASA_1_3_3_page1.png")


def page2():
    im, d, y = new_page("1.3.3 AL1 verification mapping", 2)
    d.text((MARGIN, y), "AL1 verification", font=F_SEC, fill=INK)
    y += 32
    rows = [
        ("ADA-approved IdP", "Not claimed for Supabase.", False),
        (
            "OOB codes are securely random",
            "Reset codes are issued by GoTrue (8-digit Email OTP; hashed recovery token). Invite tokens are uuid4 hex from os.urandom. TOTP secrets come from GoTrue enroll.",
            True,
        ),
        (
            "SMS OTP",
            "Not used.",
            True,
        ),
    ]
    for title, detail, ok in rows:
        color = OK if ok else INK
        d.text((MARGIN, y), title, font=F_BODY, fill=color)
        y += 24
        y = paint(d, y, [(detail, F_SMALL, MUTED)])
        y += 8
    y += 8
    d.text((MARGIN, y), "Attestation", font=F_SEC, fill=INK)
    y += 32
    y = paint(
        d,
        y,
        [
            (
                "Out-of-band password-reset verifiers for Velvet Elves are generated by Supabase Auth, not by application counters. The only OOB-style token the application mints is the invite token, which uses uuid4. TOTP secrets are generated by GoTrue.",
                F_BODY,
                INK,
            ),
        ],
    )
    im.save(OUT / "CASA_1_3_3_page2.png", "PNG")
    print("wrote", OUT / "CASA_1_3_3_page2.png")


def code_page():
    im = Image.new("RGB", (1400, 900), BG)
    d = ImageDraw.Draw(im)
    d.rectangle((0, 0, 1400, 10), fill=RULE)
    d.text((MARGIN, 36), "Velvet Elves  |  ADA-CASA AL1 evidence", font=F_SUB, fill=MUTED)
    d.text((MARGIN, 64), "1.3.3 How OOB codes are generated", font=F_H, fill=INK)
    d.text(
        (MARGIN, 98),
        "Application code: reset delegates to GoTrue; invite tokens use uuid4",
        font=F_SMALL,
        fill=MUTED,
    )
    snippet = """# app/api/v1/users.py — password reset (no local OTP)
await supabase.auth.reset_password_email(
    payload.email,
    options={"redirect_to": redirect_to},
)

# app/repositories/invitation_repository.py — invite token
token = uuid.uuid4().hex   # 32 hex; CPython uuid4 uses os.urandom

# app/services/mfa_service.py — TOTP secret from GoTrue enroll
# POST /auth/v1/factors  factor_type=totp
# secret / otpauth URI are returned by GoTrue, not minted here"""
    lines = snippet.split("\n")
    box_y = 140
    box_h = 26 * len(lines) + 48
    d.rounded_rectangle((MARGIN, box_y, 1400 - MARGIN, box_y + box_h), radius=8, fill=CODE_BG)
    y = box_y + 20
    for line in lines:
        d.text((MARGIN + 24, y), line, font=F_MONO, fill=CODE_FG)
        y += 26
    d.text(
        (MARGIN, box_y + box_h + 20),
        "CASA_1_3_3_code  |  Email OTP length 8 is a GoTrue Auth Email setting",
        font=F_FOOT,
        fill=MUTED,
    )
    im.save(OUT / "CASA_1_3_3_code.png", "PNG")
    print("wrote", OUT / "CASA_1_3_3_code.png")


if __name__ == "__main__":
    page1()
    page2()
    code_page()
